import { WizardConfig } from '../config/schema';
import { ENV_VAR_NAMES } from '../config/constants';
import { defaultConfig } from '../config/defaults';
import { escapeEnvValue } from './escaping';

interface EnvGeneratorOptions {
  includeDefaults?: boolean;
}

/**
 * Helper to create a safe environment variable line.
 * Values are escaped to prevent .env injection.
 */
function envLine(name: string, value: string | number | boolean): string {
  return `${name}=${escapeEnvValue(value)}`;
}

export function generateEnvFile(config: WizardConfig, options: EnvGeneratorOptions = {}): string {
  const { includeDefaults = false } = options;
  const lines: string[] = [];

  lines.push('# Dismissible API Configuration');
  lines.push('# Generated by Dismissible Configuration Wizard');
  lines.push('# https://dismissible.io\n');

  // Core Settings
  lines.push('# Core Settings');
  if (includeDefaults || config.core.port !== defaultConfig.core.port) {
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_PORT, config.core.port));
  }
  if (includeDefaults || config.core.storageType !== defaultConfig.core.storageType) {
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_TYPE, config.core.storageType));
  }
  if (includeDefaults || config.core.storageRunSetup !== defaultConfig.core.storageRunSetup) {
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_RUN_SETUP, config.core.storageRunSetup));
  }
  lines.push('');

  // Storage Settings
  lines.push('# Storage Settings');
  if (config.storage.type === 'postgres') {
    lines.push(
      envLine(
        ENV_VAR_NAMES.DISMISSIBLE_STORAGE_POSTGRES_CONNECTION_STRING,
        config.storage.connectionString,
      ),
    );
  } else if (config.storage.type === 'dynamodb') {
    lines.push(
      envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_DYNAMODB_TABLE_NAME, config.storage.tableName),
    );
    lines.push(
      envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_DYNAMODB_AWS_REGION, config.storage.awsRegion),
    );
    if (config.storage.awsAccessKeyId) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_STORAGE_DYNAMODB_AWS_ACCESS_KEY_ID,
          config.storage.awsAccessKeyId,
        ),
      );
    }
    if (config.storage.awsSecretAccessKey) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_STORAGE_DYNAMODB_AWS_SECRET_ACCESS_KEY,
          config.storage.awsSecretAccessKey,
        ),
      );
    }
    if (config.storage.awsSessionToken) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_STORAGE_DYNAMODB_AWS_SESSION_TOKEN,
          config.storage.awsSessionToken,
        ),
      );
    }
    if (config.storage.endpoint) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_DYNAMODB_ENDPOINT, config.storage.endpoint),
      );
    }
  } else if (config.storage.type === 'memory') {
    if (includeDefaults || config.storage.maxItems !== (defaultConfig.storage as any).maxItems) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_MEMORY_MAX_ITEMS, config.storage.maxItems),
      );
    }
    if (includeDefaults || config.storage.ttlMs !== (defaultConfig.storage as any).ttlMs) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_STORAGE_MEMORY_TTL_MS, config.storage.ttlMs));
    }
  }
  lines.push('');

  // Cache Settings
  if (config.cache.type !== 'none') {
    lines.push('# Cache Settings');
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_TYPE, config.cache.type));

    if (config.cache.type === 'redis') {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_REDIS_URL, config.cache.url));
      if (includeDefaults || config.cache.keyPrefix !== 'dismissible:cache:') {
        lines.push(
          envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_REDIS_KEY_PREFIX, config.cache.keyPrefix),
        );
      }
      if (includeDefaults || config.cache.ttlMs !== 21600000) {
        lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_REDIS_TTL_MS, config.cache.ttlMs));
      }
      if (includeDefaults || !config.cache.enableReadyCheck) {
        lines.push(
          envLine(
            ENV_VAR_NAMES.DISMISSIBLE_CACHE_REDIS_ENABLE_READY_CHECK,
            config.cache.enableReadyCheck,
          ),
        );
      }
      if (includeDefaults || config.cache.maxRetries !== 3) {
        lines.push(
          envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_REDIS_MAX_RETRIES, config.cache.maxRetries),
        );
      }
      if (includeDefaults || config.cache.connectionTimeoutMs !== 5000) {
        lines.push(
          envLine(
            ENV_VAR_NAMES.DISMISSIBLE_CACHE_REDIS_CONNECTION_TIMEOUT_MS,
            config.cache.connectionTimeoutMs,
          ),
        );
      }
    } else if (config.cache.type === 'memory') {
      if (includeDefaults || config.cache.maxItems !== 5000) {
        lines.push(
          envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_MEMORY_MAX_ITEMS, config.cache.maxItems),
        );
      }
      if (includeDefaults || config.cache.ttlMs !== 21600000) {
        lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CACHE_MEMORY_TTL_MS, config.cache.ttlMs));
      }
    }
    lines.push('');
  }

  // Swagger
  if (config.swagger.enabled) {
    lines.push('# Swagger');
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_SWAGGER_ENABLED, config.swagger.enabled));
    if (includeDefaults || config.swagger.path !== 'docs') {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_SWAGGER_PATH, config.swagger.path));
    }
    lines.push('');
  }

  // JWT Auth
  if (config.jwtAuth.enabled) {
    lines.push('# JWT Authentication');
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_ENABLED, config.jwtAuth.enabled));
    if (config.jwtAuth.wellKnownUrl) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_WELL_KNOWN_URL, config.jwtAuth.wellKnownUrl),
      );
    }
    if (config.jwtAuth.issuer) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_ISSUER, config.jwtAuth.issuer));
    }
    if (config.jwtAuth.audience) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_AUDIENCE, config.jwtAuth.audience));
    }
    if (includeDefaults || config.jwtAuth.algorithms !== 'RS256') {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_ALGORITHMS, config.jwtAuth.algorithms));
    }
    if (includeDefaults || config.jwtAuth.jwksCacheDuration !== 600000) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_JWKS_CACHE_DURATION,
          config.jwtAuth.jwksCacheDuration,
        ),
      );
    }
    if (includeDefaults || config.jwtAuth.requestTimeout !== 30000) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_REQUEST_TIMEOUT, config.jwtAuth.requestTimeout),
      );
    }
    if (includeDefaults || config.jwtAuth.priority !== -100) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_PRIORITY, config.jwtAuth.priority));
    }
    if (includeDefaults || !config.jwtAuth.matchUserId) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_MATCH_USER_ID, config.jwtAuth.matchUserId),
      );
    }
    if (includeDefaults || config.jwtAuth.userIdClaim !== 'sub') {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_USER_ID_CLAIM, config.jwtAuth.userIdClaim),
      );
    }
    if (includeDefaults || config.jwtAuth.userIdMatchType !== 'exact') {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_USER_ID_MATCH_TYPE,
          config.jwtAuth.userIdMatchType,
        ),
      );
    }
    if (config.jwtAuth.userIdMatchRegex) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_JWT_AUTH_USER_ID_MATCH_REGEX,
          config.jwtAuth.userIdMatchRegex,
        ),
      );
    }
    lines.push('');
  }

  // CORS
  if (config.cors.enabled) {
    lines.push('# CORS');
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CORS_ENABLED, config.cors.enabled));
    if (config.cors.origins) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CORS_ORIGINS, config.cors.origins));
    }
    if (includeDefaults || config.cors.methods !== 'GET,POST,DELETE,OPTIONS') {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CORS_METHODS, config.cors.methods));
    }
    if (
      includeDefaults ||
      config.cors.allowedHeaders !== 'Content-Type,Authorization,x-request-id'
    ) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_CORS_ALLOWED_HEADERS, config.cors.allowedHeaders),
      );
    }
    if (includeDefaults || !config.cors.credentials) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CORS_CREDENTIALS, config.cors.credentials));
    }
    if (includeDefaults || config.cors.maxAge !== 86400) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_CORS_MAX_AGE, config.cors.maxAge));
    }
    lines.push('');
  }

  // Helmet
  if (includeDefaults || !config.helmet.enabled) {
    lines.push('# Security Headers (Helmet)');
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_HELMET_ENABLED, config.helmet.enabled));
    if (config.helmet.enabled) {
      if (includeDefaults || !config.helmet.csp) {
        lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_HELMET_CSP, config.helmet.csp));
      }
      if (includeDefaults || !config.helmet.coep) {
        lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_HELMET_COEP, config.helmet.coep));
      }
      if (includeDefaults || config.helmet.hstsMaxAge !== 31536000) {
        lines.push(
          envLine(ENV_VAR_NAMES.DISMISSIBLE_HELMET_HSTS_MAX_AGE, config.helmet.hstsMaxAge),
        );
      }
      if (includeDefaults || !config.helmet.hstsIncludeSubdomains) {
        lines.push(
          envLine(
            ENV_VAR_NAMES.DISMISSIBLE_HELMET_HSTS_INCLUDE_SUBDOMAINS,
            config.helmet.hstsIncludeSubdomains,
          ),
        );
      }
      if (includeDefaults || config.helmet.hstsPreload) {
        lines.push(
          envLine(ENV_VAR_NAMES.DISMISSIBLE_HELMET_HSTS_PRELOAD, config.helmet.hstsPreload),
        );
      }
    }
    lines.push('');
  }

  // Validation
  if (
    includeDefaults ||
    !config.validation.disableErrorMessages ||
    !config.validation.whitelist ||
    !config.validation.forbidNonWhitelisted ||
    !config.validation.transform
  ) {
    lines.push('# Validation');
    if (includeDefaults || !config.validation.disableErrorMessages) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_VALIDATION_DISABLE_ERROR_MESSAGES,
          config.validation.disableErrorMessages,
        ),
      );
    }
    if (includeDefaults || !config.validation.whitelist) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_VALIDATION_WHITELIST, config.validation.whitelist),
      );
    }
    if (includeDefaults || !config.validation.forbidNonWhitelisted) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_VALIDATION_FORBID_NON_WHITELISTED,
          config.validation.forbidNonWhitelisted,
        ),
      );
    }
    if (includeDefaults || !config.validation.transform) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_VALIDATION_TRANSFORM, config.validation.transform),
      );
    }
    lines.push('');
  }

  // Rate Limiter
  if (config.rateLimiter.enabled) {
    lines.push('# Rate Limiter');
    lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_ENABLED, config.rateLimiter.enabled));
    if (includeDefaults || config.rateLimiter.points !== 1000) {
      lines.push(envLine(ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_POINTS, config.rateLimiter.points));
    }
    if (includeDefaults || config.rateLimiter.duration !== 1) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_DURATION, config.rateLimiter.duration),
      );
    }
    if (includeDefaults || config.rateLimiter.blockDuration !== 60) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_BLOCK_DURATION,
          config.rateLimiter.blockDuration,
        ),
      );
    }
    if (includeDefaults || config.rateLimiter.keyType !== 'ip,origin,referrer') {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_KEY_TYPE, config.rateLimiter.keyType),
      );
    }
    if (includeDefaults || config.rateLimiter.keyMode !== 'any') {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_KEY_MODE, config.rateLimiter.keyMode),
      );
    }
    if (config.rateLimiter.ignoredKeys) {
      lines.push(
        envLine(
          ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_IGNORED_KEYS,
          config.rateLimiter.ignoredKeys,
        ),
      );
    }
    if (includeDefaults || config.rateLimiter.priority !== -101) {
      lines.push(
        envLine(ENV_VAR_NAMES.DISMISSIBLE_RATE_LIMITER_PRIORITY, config.rateLimiter.priority),
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}
